### ISSUE TITLE
KafkaConsumer Error consumer is null get offset from partition:1

### ISSUE THREAD

**Issue by xuziw** [jiankunking/jstorm-kafka-plugin-demo#1]
你好。把配置文件中kafka.broker.hosts，和kafka.zookeeper.hosts改成我的。运行出错
[ERROR] 17:05:03.285 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@1fecb4e0, will change to next broker index:2
[ERROR] 17:05:03.288 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@1f162b68, will change to next broker index:0
[ERROR] 17:05:03.291 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@2aabbd07, will change to next broker index:1
[ERROR] 17:05:03.293 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@1fecb4e0, will change to next broker index:2
[ERROR] 17:05:03.293 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - Error consumer is null get offset from partition:1

**Comment by jiankunking** [comment]
需要制定kafka的主题
kafka.topic=test_one

**Comment by xuziw** [comment]
这个主题也换了。还是一样

**Comment by jiankunking** [comment]
异常信息也一样？
把你的配置贴出来吧

**Comment by xuziw** [comment]
配置：
# kafka
# kafka 消费组
kafka.client.id=kafkaspoutid
kafka.fetch.from.beginning=false
kafka.broker.partitions=4
kafka.topic=someone
kafka.broker.hosts=192.168.0.118:9092,192.168.0.119:9092,192.168.0.122:9092
kafka.zookeeper.hosts=192.168.0.119:2181,192.168.0.122:2181

storm.zookeeper.root=/kafka
异常信息：
[ERROR] 09:45:57.258 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@2d403d5f, will change to next broker index:1
[ERROR] 09:45:57.261 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@11d73f6f, will change to next broker index:2
[ERROR] 09:45:57.264 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@26b54164, will change to next broker index:0
[ERROR] 09:45:57.266 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@2d403d5f, will change to next broker index:1
[ERROR] 09:45:57.266 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - Error consumer is null get offset from partition:1
[ERROR] 09:45:57.271 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@11d73f6f, will change to next broker index:2
[ERROR] 09:45:57.273 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@26b54164, will change to next broker index:0
[ERROR] 09:45:57.276 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@2d403d5f, will change to next broker index:1
[ERROR] 09:45:57.279 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@11d73f6f, will change to next broker index:2
[ERROR] 09:45:57.279 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - Error consumer is null get offset from partition:2
[ERROR] 09:45:59.256 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@2d403d5f, will change to next broker index:1
[ERROR] 09:45:59.259 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@11d73f6f, will change to next broker index:2
[ERROR] 09:45:59.262 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@26b54164, will change to next broker index:0
[ERROR] 09:45:59.264 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - findLeader error, broker:jiankunking.kafkajstorm.kafka.Host@2d403d5f, will change to next broker index:1
[ERROR] 09:45:59.264 [kafkaSpout:4-MultipleThreadSpoutExecutors] j.kafkajstorm.kafka.KafkaConsumer - Error consumer is null get offset from partition:3

**Comment by jiankunking** [comment]
1、确保你的kafka、zookeeper集群运行正常
2、确保kafka主题正确
3、屏蔽掉配置文件中
#storm.zookeeper.root=/kafka

再试一下

**Comment by xuziw** [comment]
kafka.fetch.from.beginning这个参数有什么作用？
我设置成true就可以了。

**Comment by jiankunking** [comment]
kafka 数据是否从头拉取

你现在kafka集群中没有实时产生的数据？

**Comment by xuziw** [comment]
我去。还要这样啊。我都是先发送部分消息，然后在去消费。

**Comment by xuziw** [comment]
logback好像也有问题：
11:00:29,397 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@25:25 - RuntimeException in Action for tag [rollingPolicy] java.lang.IndexOutOfBoundsException: No group 1
	at java.lang.IndexOutOfBoundsException: No group 1
	at 	at java.util.regex.Matcher.group(Matcher.java:538)
	at 	at ch.qos.logback.core.rolling.helper.FileFilterUtil.extractCounter(FileFilterUtil.java:109)
	at 	at ch.qos.logback.core.rolling.helper.FileFilterUtil.findHighestCounter(FileFilterUtil.java:93)
	at 	at ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP.computeCurrentPeriodsHighestCounterValue(SizeAndTimeBasedFNATP.java:65)
	at 	at ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP.start(SizeAndTimeBasedFNATP.java:49)
	at 	at ch.qos.logback.core.rolling.TimeBasedRollingPolicy.start(TimeBasedRollingPolicy.java:90)
	at 	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:167)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at 	at com.alibaba.jstorm.utils.JStormUtils.<clinit>(JStormUtils.java:95)
	at 	at com.xqcx.kafka.KafkaSpoutConfig.convertHosts(KafkaSpoutConfig.java:91)
	at 	at com.xqcx.kafka.KafkaSpoutConfig.configure(KafkaSpoutConfig.java:50)
	at 	at com.xqcx.CustomCounterTopology.main(CustomCounterTopology.java:38)

**Comment by jiankunking** [comment]
大哥logback这么明显的问题，你就不能debug一下？

**Comment by xuziw** [comment]
我把kafka.broker.hosts，和kafka.zookeeper.hosts端口去掉就报这两行了：
at 	at com.xqcx.kafka.KafkaSpoutConfig.configure(KafkaSpoutConfig.java:54)
at 	at com.xqcx.CustomCounterTopology.main(CustomCounterTopology.java:38)

**Comment by xuziw** [comment]
只要第一次调用：JStormUtils.parseInt() ....就会报那个错。
